/**
 * Application constants and configuration values
 */

export const COLOR_HUES = [
  "Blue",
  "Cyan",
  "Green",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "Yellow",
  "Gold",
  "Maroon",
  "Olive",
  "Slate",
  "Violet",
  "Gray",
];

export const ICONS = {
  FOLDER: "#_iconFolder",
  DIR: "#_iconDir",
  LINK: "#_iconLink",
  STYLE: "#_iconStyle",
  SCRIPT: "#_iconScript",
  COG: "#_iconCog",
  DOCS: "#_iconDocs",
  VECTOR: "#_iconVector",
  PHOTO: "#_iconPhoto",
  VIDEO: "#_iconVideo",
  AUDIO: "#_iconAudio",
  ARCHIVE: "#_iconArchive",
  DATABASE: "#_iconDatabase",
  CHART: "#_iconChart",
  LOCK: "#_iconLock",
  FILE: "#_iconFile",
};

export const FILE_EXTENSIONS = {
  html: ICONS.LINK,
  htm: ICONS.LINK,
  css: ICONS.STYLE,
  scss: ICONS.STYLE,
  sass: ICONS.STYLE,
  less: ICONS.STYLE,
  stylus: ICONS.STYLE,

  js: ICONS.SCRIPT,
  ts: ICONS.SCRIPT,
  jsx: ICONS.SCRIPT,
  tsx: ICONS.SCRIPT,
  mjs: ICONS.SCRIPT,
  cjs: ICONS.SCRIPT,

  json: ICONS.COG,
  config: ICONS.COG,
  conf: ICONS.COG,
  ini: ICONS.COG,
  yaml: ICONS.COG,
  yml: ICONS.COG,
  toml: ICONS.COG,
  env: ICONS.COG,
  gitignore: ICONS.COG,
  gitconfig: ICONS.COG,
  npmrc: ICONS.COG,
  babelrc: ICONS.COG,
  eslintrc: ICONS.COG,
  prettierrc: ICONS.COG,

  md: ICONS.DOCS,
  txt: ICONS.DOCS,
  readme: ICONS.DOCS,
  rst: ICONS.DOCS,
  doc: ICONS.DOCS,
  docx: ICONS.DOCS,
  pdf: ICONS.DOCS,

  svg: ICONS.VECTOR,
  ico: ICONS.VECTOR,

  png: ICONS.PHOTO,
  jpg: ICONS.PHOTO,
  jpeg: ICONS.PHOTO,
  gif: ICONS.PHOTO,
  webp: ICONS.PHOTO,
  avif: ICONS.PHOTO,
  bmp: ICONS.PHOTO,
  tiff: ICONS.PHOTO,
  heic: ICONS.PHOTO,
  heif: ICONS.PHOTO,

  mp4: ICONS.VIDEO,
  avi: ICONS.VIDEO,
  mkv: ICONS.VIDEO,
  webm: ICONS.VIDEO,
  mov: ICONS.VIDEO,
  wmv: ICONS.VIDEO,
  flv: ICONS.VIDEO,
  m4v: ICONS.VIDEO,

  mp3: ICONS.AUDIO,
  wav: ICONS.AUDIO,
  flac: ICONS.AUDIO,
  aac: ICONS.AUDIO,
  ogg: ICONS.AUDIO,
  wma: ICONS.AUDIO,
  m4a: ICONS.AUDIO,

  zip: ICONS.ARCHIVE,
  rar: ICONS.ARCHIVE,
  "7z": ICONS.ARCHIVE,
  tar: ICONS.ARCHIVE,
  gz: ICONS.ARCHIVE,
  bz2: ICONS.ARCHIVE,
  xz: ICONS.ARCHIVE,

  sql: ICONS.DATABASE,
  db: ICONS.DATABASE,
  sqlite: ICONS.DATABASE,
  sqlite3: ICONS.DATABASE,
  mdb: ICONS.DATABASE,
  accdb: ICONS.DATABASE,

  csv: ICONS.CHART,
  tsv: ICONS.CHART,
  xlsx: ICONS.CHART,
  xls: ICONS.CHART,
  ods: ICONS.CHART,

  key: ICONS.LOCK,
  pem: ICONS.LOCK,
  p12: ICONS.LOCK,
  pfx: ICONS.LOCK,
  cert: ICONS.LOCK,
  crt: ICONS.LOCK,
  der: ICONS.LOCK,
};

export const SPECIAL_FILES = {
  package: { extensions: ["json"], icon: ICONS.COG },
  readme: { extensions: ["md", "txt", ""], icon: ICONS.DOCS },
  changelog: { extensions: ["md", "txt", ""], icon: ICONS.DOCS },
  license: { extensions: ["md", "txt", ""], icon: ICONS.DOCS },
};

export const CONFIG_PATTERNS = ["config", "settings"];

export const DRAWING = {
  CORNER_RADIUS: 8,
  HORIZONTAL_LENGTH: 16,
  STROKE_WIDTH: 0.5,
  FOLDER_STROKE_OPACITY: 0.4,
  STROKE_DASHARRAY: "2, 2",
  CHILD_OFFSET_MULTIPLIER: 8,
  HORIZONTAL_OFFSET_FACTOR: 0.5,
  REDRAW_DELAY: 50,
};

export const CSS_COLORS = {
  lightWhite: "#f8f8ff",
  darkWhite: "#dfe2e8",
  lightBlack: "#2f4f4f",
  darkBlack: "#1a3737",
  lightBlue: "#6c8eef",
  darkBlue: "#5469d4",
  lightCyan: "#3a97d4",
  darkCyan: "#067ab8",
  lightGold: "#ffd700",
  darkGold: "#daa520",
  lightGray: "#8e8e8e",
  darkGray: "#787878",
  lightGreen: "#1ea672",
  darkGreen: "#09825d",
  lightMaroon: "#9c3f3f",
  darkMaroon: "#741f1f",
  lightOlive: "#808000",
  darkOlive: "#556b2f",
  lightOrange: "#e56f4a",
  darkOrange: "#c44c34",
  lightPink: "#f472b6",
  darkPink: "#ec4899",
  lightPurple: "#9c82db",
  darkPurple: "#8260c3",
  lightRed: "#ed5f74",
  darkRed: "#cd3d64",
  lightSlate: "#8792a2",
  darkSlate: "#697386",
  lightViolet: "#4a50aa",
  darkViolet: "#6c68ee",
  lightYellow: "#d97917",
  darkYellow: "#bb5504",

  white: "ghostwhite",
  black: "darkslategray",
  blue: "dodgerblue",
  cyan: "turquoise",
  gold: "goldenrod",
  gray: "silver",
  green: "mediumseagreen",
  maroon: "indianred",
  olive: "olive",
  orange: "darkorange",
  pink: "hotpink",
  purple: "mediumpurple",
  red: "crimson",
  slate: "slategray",
  violet: "mediumslateblue",
  yellow: "gold",
};

export const LAYOUT = {
  ICON_SIZE: "0.875rem",
  NODE_PADDING: "0.125rem 0.375rem",
  HIERARCHY_GAP: "0.1rem",
  BORDER_RADIUS: "0.25rem",
  TRANSITION: "all 0.15s ease-in-out",
};

export const EVENTS = {
  HOVER_HIGHLIGHT_CLASS: "hierarchy-highlight",
  FOLDER_EXPANDED_ATTRIBUTE: "aria-expanded",
  EMPTY_FOLDER_CLASS: "empty-folder",
};
